const leafletMapTab = {
  state: {
    varName: 'WorldGeoJSON',
    outFile: 'world-geojson.js'
  },

  geoJsonSourceUrl: 'https://flankspeed.sharepoint-mil.us/sites/Prometheus/_layouts/15/download.aspx?UniqueId=53abd0629f0349768a6148f623030462&e=ksU9lU',

  init() {
    $(document).on('click', '#lm-geojson-source-btn', async (e) => {
      e.preventDefault();
      await this.copyGeoJsonLink();
    });
    $(document).on('input', '#lm-var-name', (e) => {
      this.state.varName = this._normalizeVarName(e.target.value);
      if (e.target.value !== this.state.varName) e.target.value = this.state.varName;
    });
    $(document).on('input', '#lm-out-file', (e) => {
      this.state.outFile = this._normalizeOutFile(e.target.value);
      if (e.target.value !== this.state.outFile) e.target.value = this.state.outFile;
    });
    $(document).on('click', '#lm-convert-btn', () => this.convertAndSave());
  },

  _normalizeVarName(value) {
    return String(value || '').trim() || 'WorldGeoJSON';
  },

  _normalizeOutFile(value) {
    return String(value || '').trim() || 'world-geojson.js';
  },

  syncFormFromState() {
    const varInput = document.getElementById('lm-var-name');
    const outFileInput = document.getElementById('lm-out-file');
    if (varInput) varInput.value = this.state.varName;
    if (outFileInput) outFileInput.value = this.state.outFile;
  },

  resetUi() {
    this.syncFormFromState();
    const fileInput = document.getElementById('lm-file');
    const statusEl = document.getElementById('lm-status');
    if (fileInput) fileInput.value = '';
    if (statusEl) statusEl.textContent = '';
  },

  async copyGeoJsonLink() {
    if (typeof window.copyLinkAndPrompt === 'function') {
      await window.copyLinkAndPrompt(this.geoJsonSourceUrl, 'Leaflet GeoJSON');
      return;
    }
    try {
      await navigator.clipboard.writeText(this.geoJsonSourceUrl);
      alert('GeoJSON link copied to clipboard.');
    } catch (error) {
      alert('Could not copy link automatically. Copy this URL manually:\n\n' + this.geoJsonSourceUrl);
    }
  },

  async convertAndSave() {
    const statusEl = document.getElementById('lm-status');
    const fileInput = document.getElementById('lm-file');
    const varNameInput = document.getElementById('lm-var-name');
    const outFileInput = document.getElementById('lm-out-file');

    this.state.varName = this._normalizeVarName(varNameInput && 'value' in varNameInput ? varNameInput.value : this.state.varName);
    this.state.outFile = this._normalizeOutFile(outFileInput && 'value' in outFileInput ? outFileInput.value : this.state.outFile);
    this.syncFormFromState();
    if (statusEl) statusEl.textContent = '';

    if (!fileInput || !fileInput.files || !fileInput.files[0]) {
      alert('Please choose a GeoJSON file first.');
      return;
    }
    if (!loadFolder || !loadFolder.fileHandle) {
      alert('Please load a directory first.');
      return;
    }

    try {
      const selectedFile = fileInput.files[0];
      const rawText = await selectedFile.text();
      let json;
      try {
        json = JSON.parse(rawText);
      } catch (error) {
        throw new Error('Selected file is not valid JSON/GeoJSON. ' + error.message);
      }

      const isLikelyGeoJson = json && (
        json.type === 'FeatureCollection' ||
        json.type === 'Feature' ||
        json.type === 'GeometryCollection'
      );
      if (!isLikelyGeoJson && !confirm('The JSON does not look like GeoJSON. Save anyway?')) {
        return;
      }

      const jsPayload =
        '// Generated by Warfighter Coder Leaflet Map tool\n' +
        '// Offline GeoJSON bundle for use with Leaflet\n' +
        `window.${this.state.varName} = ${JSON.stringify(json)};\n`;

      const fileHandle = await loadFolder.fileHandle.getFileHandle(this.state.outFile, { create: true });
      const writable = await fileHandle.createWritable();
      await writable.write(jsPayload);
      await writable.close();

      loadFolder.fileStructure = await loadFolder.recursivelyReadDirectory([], loadFolder.fileHandle);
      loadFolder.refreshFileTree();

      if (statusEl) statusEl.textContent = `Saved ${this.state.outFile}.`;
      alert(`Saved ${this.state.outFile} to your project.`);
    } catch (error) {
      console.error('Leaflet GeoJSON convert/save failed:', error);
      if (statusEl) statusEl.textContent = 'Error: ' + error.message;
      alert('Error: ' + error.message);
    }
  },

  getSnippetString() {
    const varName = this.state.varName || 'WorldGeoJSON';
    const outFile = this.state.outFile || 'world-geojson.js';
    return `<!-- Development: Use Leaflet CDN (switch to local files for offline builds) -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

<!-- Include your converted GeoJSON bundle -->
<script src="${outFile}"></script>

<style>
  #map { width: 100%; height: 480px; background: #0c0f13; }
  .leaflet-interactive:focus { outline: none; }
</style>
<div id="map"></div>

<script>
  (function () {
    if (!window.${varName}) {
      console.error('Missing ${varName}');
      return;
    }

    var map = L.map('map', {
      zoomControl: true,
      attributionControl: false,
      worldCopyJump: true,
      keyboard: false
    });

    function shiftedFeature(feature, dx) {
      try {
        var clone = JSON.parse(JSON.stringify(feature));
        function shiftCoords(coords) {
          if (typeof coords[0] === 'number') {
            coords[0] += dx;
            return coords;
          }
          for (var i = 0; i < coords.length; i++) shiftCoords(coords[i]);
          return coords;
        }
        if (clone && clone.geometry && clone.geometry.coordinates) shiftCoords(clone.geometry.coordinates);
        return clone;
      } catch (error) {
        return feature;
      }
    }

    function wrapCollection(fc) {
      if (!fc || fc.type !== 'FeatureCollection') return fc;
      var wrapped = { type: 'FeatureCollection', features: [] };
      for (var i = 0; i < fc.features.length; i++) {
        var feature = fc.features[i];
        wrapped.features.push(feature);
        wrapped.features.push(shiftedFeature(feature, 360));
        wrapped.features.push(shiftedFeature(feature, -360));
      }
      return wrapped;
    }

    var data = window.${varName};
    if (data && data.type === 'FeatureCollection') data = wrapCollection(data);

    var layer = L.geoJSON(data, {
      style: function () {
        return { color: '#66b3ff', weight: 1, fillColor: '#225b91', fillOpacity: 0.35 };
      },
      onEachFeature: function (feature, featureLayer) {
        var name = feature && feature.properties && (feature.properties.name || feature.properties.NAME || feature.properties.admin);
        if (name) featureLayer.bindTooltip(String(name));
        featureLayer.on('click', function (e) {
          if (e && e.originalEvent) e.originalEvent.preventDefault();
        });
        featureLayer.on('mousedown', function (e) {
          if (e && e.originalEvent) e.originalEvent.preventDefault();
        });
      }
    }).addTo(map);

    try {
      map.fitBounds(layer.getBounds(), { padding: [10, 10] });
    } catch (error) {
      map.setView([20, 0], 2);
    }
  })();
</script>`;
  },

  buildAdvancedPrompt(contextText) {
    const snippet = this.getSnippetString();
    const userContext = String(contextText || '').trim() || '[describe the map layout, overlays, and interactions]';
    return `Add an offline-friendly Leaflet map to my existing static HTML/JavaScript app.

Map requirements for this app:
${userContext}

Implementation requirements:
- Use vanilla JavaScript.
- Use Leaflet CDN assets during development, but structure the code so the files can be swapped to local copies for offline deployment later.
- Render polygons from a local JavaScript bundle that defines window.${this.state.varName} from ${this.state.outFile}.
- Do not use online tile servers. Use a styled background plus GeoJSON vector layers only.
- Keep the existing layout and styles where possible.
- Add hover tooltips for meaningful labels such as country or area name.
- Prevent click-selection outlines or other click artifacts on polygons.
- Support continuous horizontal panning by duplicating features at +/- 360 degrees longitude.
- If the map data file does not exist yet, tell me exactly where it should be referenced and assume it will be created as ${this.state.outFile}.
- IMPORTANT: When modifying files, provide the COMPLETE file content with the new code integrated. Do NOT provide snippets or diffs.

Reference integration snippet:
----- SNIPPET START -----
${snippet}
----- SNIPPET END -----`;
  }
};
